In [0]:
import numpy as np

In [0]:
A = np.matrix([[1,-1],
               [2, 1]])

In [17]:
A

matrix([[ 1, -1],
        [ 2,  1]])

In [20]:
A**2-2*A+3

matrix([[0, 3],
        [3, 0]])

In [21]:
b = np.matrix([[-1], [2]])
b

matrix([[-1],
        [ 2]])

In [22]:
x = np.linalg.solve(A, b)
x

matrix([[0.33333333],
        [1.33333333]])

In [23]:
A*x

matrix([[-1.],
        [ 2.]])

In [24]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[ 0.33333333,  0.33333333],
        [-0.66666667,  0.33333333]])

In [25]:
A*Ainv

matrix([[1.00000000e+00, 5.55111512e-17],
        [0.00000000e+00, 1.00000000e+00]])

In [26]:
np.linalg.det(A)

2.9999999999999996